Moved Rails.start and Turbolinks.start into the DOM content load block
psu-libraries/psulib_blacklight pull request #1070
Opened 2022-10-31 20:57 UTC by ajkiessl

2022-11-03 00:46 UTC, banukutlu commented
@ajkiessl These changes were not affecting availability, sorry if this was a misunderstanding, the issue is with bookmarks. For example, when I try to bookmark a record on search results and click again to remove bookmark, I get an error as below. Similarly, if a record is already bookmarked, I remove the bookmark and click again to bookmark, I am getting an error again. It seems it is happening when clicked for the same record consecutively. Same behavior on bookmarks page as well. 

<img width="1021" alt="Screen Shot 2022-11-02 at 8 36 41 PM" src="https://user-images.githubusercontent.com/6477867/199627592-6f44279b-33c9-4d12-8878-dada52df7c1d.png">

2022-11-03 00:49 UTC, banukutlu requested changes
@ajkiessl These changes were not affecting availability, sorry if this was a misunderstanding, the issue is with bookmarks. For example, when I try to bookmark a record on search results and click again to remove bookmark, I get an error as below. Similarly, if a record is already bookmarked, I remove the bookmark and click again to bookmark, I am getting an error again. It looks like it is happening when clicked for the same record consecutively. Same behavior on bookmarks page as well. It is working on qa and catalog. 

<img width="1021" alt="Screen Shot 2022-11-02 at 8 36 41 PM" src="https://user-images.githubusercontent.com/6477867/199627592-6f44279b-33c9-4d12-8878-dada52df7c1d.png">

2022-11-03 14:52 UTC, ajkiessl commented
Looks like adding `rails-ujs` back in fixed this.  The CSRF protection was blocking subsequent ajax calls.  Not too sure _why_ `rails-ujs` fixes this, but it does.  

I added a test for adding, removing and re-adding a bookmark.  It won't actually catch this issue since it looks like the CSRF protection doesn't block these requests in development and test.  I guess it doesn't hurt to have the test though.

2022-11-07 15:16 UTC, ajkiessl commented
> I added a test for adding, removing and re-adding a bookmark. It won't actually catch this issue since it looks like the CSRF protection doesn't block these requests in development and test. I guess it doesn't hurt to have the test though.

I found a way to turn on CSRF protection in the test.

2022-11-07 16:31 UTC, banukutlu commented on spec/features/bookmarks_spec.rb
> +    ActionController::Base.allow_forgery_protection = true
👌🏻

2022-11-07 16:32 UTC, banukutlu approved these changes
looks great, thanks @ajkiessl 🙌🏻

2022-11-07 16:32 UTC, merged