5xx error link syntax fix
psu-libraries/psulib_blacklight pull request #1103
Opened 2022-12-09 16:55 UTC by Smullz622

2022-12-09 17:27 UTC, whereismyjetpack submitted a review, later dismissed

2022-12-12 17:14 UTC, banukutlu commented
CC shows a big coverage change 👀

2022-12-12 17:21 UTC, banukutlu requested changes

2022-12-12 17:21 UTC, banukutlu commented on config/locales/blacklight.en.yml
> +        request_error: "Sorry, our search index experienced a problem. Please try again in a moment. If this error persists, please <a href="https://libraries.psu.edu/website-feedback">report the iss
There are double quotes inside double quotes here, test is failing with syntax error. Maybe sth like below? Of course needs to update references.

```suggestion
        request_error: 
          html: 'Sorry, our search index experienced a problem. Please try again in a moment. If this error persists, please <a href="https://libraries.psu.edu/website-feedback">report the issue</a> to Libraries Strategic Technology.'
```

2022-12-12 22:16 UTC, ajkiessl approved these changes
Not sure how to test this, but the syntax looks good to me.  I think the translation field either needs to be called "html" or end with "_html" for the html to render properly, so I think this should be good.

2023-01-04 16:25 UTC, banukutlu approved these changes
thanks @Smullz622

2023-01-04 16:25 UTC, merged