size selector default to 20
psu-libraries/psulib_blacklight pull request #919
Opened 2021-11-30 18:00 UTC by banukutlu

Closes #899

2021-12-01 15:30 UTC, nicktiberi approved these changes
Sorry I missed this in the first PR! I gave it a premature green light... 🤦 

I just checked out this branch and tested locally and it works great. 👍

2021-12-01 15:56 UTC, awead requested changes
One minor suggestion.

2021-12-01 15:56 UTC, awead commented on app/services/browse_list.rb
> +  def initialize(field:, page: 1, length: 20, prefix: nil)
we should probably set this as `length: ShelfListPresenter::DEFAULT`

2021-12-02 14:13 UTC, awead approved these changes

2021-12-02 14:21 UTC, merged